### ISSUE TITLE
Microsoft Edge crashes

### ISSUE THREAD

**Issue by gyrantol** [jflieben/OnedriveMapperV5#1]
Whilst running the mapper on 5.15 Edge crashes with the following events in powershell.

INFO | -----11/09/2023 13:01:59 OneDriveMapper v5.15 - adminsv on AAREON-RDSH06 starting-----
INFO | OnedriveMapper is running from C:\Users\AdminSV\Downloads
INFO | Script elevation level: User
INFO | Set TLS protocol version to prefer v1.2
INFO | Loading Selenium driver (C:\Users\AdminSV\AppData\Roaming\WebDriver.dll)
INFO | Selenium driver present and not blocked by zoning, loading...

GAC    Version        Location                                                                                                                                           
---    -------        --------                                                                                                                                           
False  v4.0.30319                                                                                                                                                        
INFO | Selenium loaded successfully
INFO | Loading CookieSetter...
INFO | Test cookie set successfully
INFO | You are adminsv running on Windows 10 with Powershell version 5 and Edge version 119.0.2151.44
INFO | .NET V4 client version: 4.8.03761
INFO | loading interop service
INFO | interop service loaded
ERROR | ERROR: WebDav File Locking support is enabled, this could cause files to become locked in your OneDrive or Sharepoint site
WARNING | Maximum file upload size is set to 48 MB
INFO | NOTICE: IE Security zones ambiguous - checking both computer and user
INFO | NOTICE: lhp-my.sharepoint.com found in IE Trusted Sites on user level
INFO | NOTICE: lhp.sharepoint.com found in IE Trusted Sites on user level
INFO | Detected running explorer process
INFO | IE Automatic Proxy Detection is not yet disabled, attempting to disable...
INFO | IE Automatic Proxy Detection disabled
INFO | Loading Edge driver C:\Users\AdminSV\AppData\Roaming\msedgedriver.exe
INFO | Discovered Edge driver v119.0.2151.44 at C:\Users\AdminSV\AppData\Roaming\msedgedriver.exe
INFO | Your Edge version and Edge Driver version match
INFO | Edge driver present and not blocked by zoning, loading...
ERROR | Failed to load Edge driver, cannot continue.  error details: Exception calling ".ctor" with "2" argument(s): "session not created: Microsoft Edge failed to start:
 crashed.
  (chrome not reachable)
  (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has
 crashed.) (SessionNotCreated)"
You cannot call a method on a null-valued expression.

I can't locate anything in event viewer why Edge crashed. Any help would be most appreciated.

**Comment by jflieben** [comment]
this has been reported once or twice, it's something local but I don't remember what the root causes were for the customers in question. I recommend going from a clean working machine to a fully configured machine (e.g. intune/mdm/gpo/proxy/firewall etc etc) and seeing when the issue starts occuring.

**Comment by gyrantol** [comment]
I have found event viewer entries now.. 

Fault bucket 1905927320539112566, type 5
Event Name: crashpad_exp
Response: Not available
Cab Id: 0

Problem signature:
P1: msedge.exe
P2: 119.0.2151.58
P3: msedge.dll
P4: 119.0.2151.58
P5: 34589858
P6: browser
P7: 0x80000003
P8: 0
P9: 
P10: 

Attached files:
\\?\C:\Users\VickeS\AppData\Roaming\Lieben Consultancy\OnedriveMapper\Profile\Crashpad\temp\2170fc65-05cb-4aa8-8984-54f4b6e1312c_crashinfo.txt
\\?\C:\ProgramData\Microsoft\EdgeUpdate\Log\MicrosoftEdgeUpdate.log
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBAD.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Critical_msedge.exe_85398df3ccbabf17e9118190d01ed78c188dc56_00000000_484726c7

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1919c351-7fbc-11ee-aae9-0022483f0e6d
Report Status: 0
Hashed bucket: 8470d782883deb599a7336cccc722476

**Comment by jflieben** [comment]
closing as stale issue. Comment was not (yet) followed up on or unknown (clean machine test)
