### ISSUE TITLE
Script wont continue after login

### ISSUE THREAD

**Issue by ItsMeMistral** [jflieben/OnedriveMapperV5#10]
Script ran good, tried installing it today on a new pc. Both 5.14 and 5.15 won't continue after logging into the account. Opens Delve.
If I close Delve the powershell gives indefinite errors.

![Schermafbeelding 2024-08-30 151439](https://github.com/user-attachments/assets/11b0bf3f-0699-4c8a-a6e0-054feb024155)

**Comment by jflieben** [comment]
@ItsMeMistral are you sure the user is licensed for Onedrive / can access their onedrive through the browser?

**Comment by ItsMeMistral** [comment]
Currently this user doesn't have a license, but I have also tried it with a licensed user. That account get's the same problem. Also opens Delve.

**Comment by jflieben** [comment]
@ItsMeMistral I've only seen this ever for users that were not (correctly) licensed or licensed only minutes ago.

Perhaps try to license the user and log in in an hour or so, and make sure onedrive works through the browser for that user.

**Comment by ItsMeMistral** [comment]
Seems to work after adding the license, weird that it didn't work with the other licensed user.
Also rebooted inbetween.
Thank You.
