### ISSUE TITLE
Script information different from Sharepoint information

### ISSUE THREAD

**Issue by mateus-strobel** [jflieben/OnedriveMapperV5#2]
Hello!

First of all, thank you very much for the script, we have used it a lot here!

I received some support requests, some folders are appearing mapped to the user, however, with nothing inside. Accessing Sharepoint through the normal website, the files are there normally.

In Script, I don't get any error message. Do you have any idea what could be causing this 'bug'?
This bug is occurring for more than one user from different tenants.

**Comment by jflieben** [comment]
Hi @mateus-strobel , I've only seen this happen in cases where the mapped document library had a very large number of items (total items, including in subfolders). This was resolved by splitting up and/or cleaning up. The WebDAV client probably has a max # of items it can iterate.

**Comment by mateus-strobel** [comment]
Hi @jflieben, thanks for the feedback.

I thought about this possibility, but there are other users accessing the same folder and viewing all the files.
Anyway, where can I confirm the maximum number of items that is configured in the script? And what is the maximum limit?

**Comment by jflieben** [comment]
@mateus-strobel this is not something configured in the script, seeing or not seeing items is either a webdav client issue or a rights/spo issue, the script has no configuration for limiting the number of items returned.

**Comment by mateus-strobel** [comment]
Users viewing the folder's data have the same permissions as the affected user. The user viewed the files and then stopped viewing them from one day to the next.

Where do I see this WebDav client configuration?

Another case I have is a user who only sees 56 items in a folder out of a total of 600. If I move the items to a previous folder, she only sees 56 items. If I clone the folder items to a new folder, the behavior is the same.

**Comment by jflieben** [comment]
https://learn.microsoft.com/en-us/iis/publish/using-webdav/using-the-webdav-redirector

if you are seeing different behavior between two users with identical rights on SpO and you've triple checked that at all levels then the only two other possibilities are the client cache / local profile of the user or software on their machine doing some filtering (e.g. A/V).
