### ISSUE TITLE
Encountering problems with $forceHideEdge set to $true

### ISSUE THREAD

**Issue by dgiaffe** [jflieben/OnedriveMapperV5#3]
Hello, I am not sure if that is the newer versions of Edge (v125+), but we've been having issue with OneDriveMapper for a few weeks, sporadically. It looks like I was able to fix it by modifying the block

`if($forceHideEdge){
       $global:edgeOptions.addArguments("headless")
} `

to 

`if($forceHideEdge){
       $global:edgeOptions.addArguments("--headless=new")
} `

Otherwise, setting `$forceHideEdge = $false` also fixed the issue, but that wasn't an option for us.

Hope this can help someone

**Comment by jflieben** [comment]
Thanks for sharing this JF! I've added it to the latest commit :)
