### ISSUE TITLE
Edge Driver Issue:  Looking for Input

### ISSUE THREAD

**Issue by linden-seitz-bcorg** [jflieben/OnedriveMapperV5#5]
Looking for some input as to the behavior below resulting in the following.  It was resolved by a subsequent logout/login - data on that also below.  Any help is appreciated!

RROR | Failed to load Edge driver, cannot continue.  error details: Exception setting "Size":

08/07/2024 15:45:47 | INFO | Loading Edge driver C:\Users\joe_test_2\AppData\Roaming\msedgedriver.exe
08/07/2024 15:45:55 | WARNING | Edge driver not present at C:\Users\joe_test_2\AppData\Roaming\msedgedriver.exe, will try to download automatically from trusted source
08/07/2024 15:46:03 | INFO | Your Edge version (127.0.2651.86) and Edge Driver version () do not match, attempting to auto update
08/07/2024 15:46:10 | INFO | Downloading latest version from https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/127.0.2651.86/edgedriver_win64.zip to C:\Users\joe_test_2\AppData\Roaming
08/07/2024 15:56:57 | INFO | Updated to version  from https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/127.0.2651.86/edgedriver_win64.zip to C:\Users\joe_test_2\AppData\Roaming
08/07/2024 15:56:57 | INFO | Edge driver present and not blocked by zoning, loading...
08/07/2024 15:58:34 | ERROR | Failed to load Edge driver, cannot continue.  error details: Exception setting "Size": "The HTTP request to the remote WebDriver server for URL http://localhost:63353/session/8ed1271d48008ee09110398ab724b940/window/rect timed out after 60 seconds."
08/07/2024 15:59:14 | WARNING | restartExplorer is set to False, if you're redirecting folders they may not show up

Successful launch:
08/07/2024 16:29:19 | INFO | Loading Edge driver C:\Users\joe_test_2\AppData\Roaming\msedgedriver.exe
08/07/2024 16:29:21 | INFO | Discovered Edge driver v127.0.2651.86 at C:\Users\joe_test_2\AppData\Roaming\msedgedriver.exe
08/07/2024 16:29:21 | INFO | Your Edge version and Edge Driver version match

**Comment by jflieben** [comment]
hi @linden-seitz-bcorg are you using a proxy or vpn or something similar? the 'http://localhost:63353' error is unexpected...

**Comment by linden-seitz-bcorg** [comment]
thank you for your analysis, you were spot on!  Once I tracked it down I found out that we are slowly deploying a full system proxy and it hit one of our test machines.  Issue solved many thanks!

**Comment by jflieben** [comment]
Thanks for responding :)
