### ISSUE TITLE
OneDrive Mapper fails to complete

### ISSUE THREAD

**Issue by Adept-James** [jflieben/OnedriveMapperV5#9]
Hello,

We're experiencing an issue with one machine at the moment, which is failing to open the office sign in screen. The Edge window opens, and it says google.nl at the top with a blank page, but doesn't go any further. The logs show the following

`08/29/2024 15:55:29 | INFO | -----08/29/2024 15:55:29 OneDriveMapper v5.15 - [user redacted for privacy] on X1WORK starting-----
08/29/2024 15:55:29 | INFO | OnedriveMapper is running from C:\Users\[user redacted for privacy]\Office_365_System_Files_Do_Not_Delete
08/29/2024 15:55:29 | INFO | Script elevation level: User
08/29/2024 15:55:30 | INFO | Set TLS protocol version to prefer v1.2
08/29/2024 15:55:30 | INFO | Loading Selenium driver (C:\Users\[user redacted for privacy]\Office_365_System_Files_Do_Not_Delete\WebDriver.dll)
08/29/2024 15:55:30 | INFO | Selenium driver present and not blocked by zoning, loading...
08/29/2024 15:55:30 | INFO | Selenium loaded successfully
08/29/2024 15:55:30 | INFO | Loading CookieSetter...
08/29/2024 15:55:30 | INFO | Test cookie set successfully
08/29/2024 15:55:30 | INFO | You are [user redacted for privacy] running on Windows 10 with Powershell version 5 and Edge version 128.0.2739.42
08/29/2024 15:55:30 | INFO | .NET V4 client version: 4.8.09032
08/29/2024 15:55:30 | INFO | loading interop service
08/29/2024 15:55:30 | INFO | interop service loaded
08/29/2024 15:55:30 | WARNING | Maximum file upload size is set to 48 MB
08/29/2024 15:55:30 | INFO | NOTICE: IE Security zones ambiguous - checking both computer and user
08/29/2024 15:55:30 | INFO | NOTICE: [tenant redacted for privacy]-my.sharepoint.com found in IE Trusted Sites on user level
08/29/2024 15:55:30 | INFO | NOTICE: [tenant redacted for privacy].sharepoint.com found in IE Trusted Sites on user level
08/29/2024 15:55:31 | INFO | Detected running explorer process
08/29/2024 15:55:31 | INFO | IE Automatic Proxy Detection is already disabled
08/29/2024 15:55:31 | INFO | Loading Edge driver C:\Users\[user redacted for privacy]\Office_365_System_Files_Do_Not_Delete\msedgedriver.exe
08/29/2024 15:55:31 | INFO | Discovered Edge driver v128.0.2739.42 at C:\Users\[user redacted for privacy]\Office_365_System_Files_Do_Not_Delete\msedgedriver.exe
08/29/2024 15:55:31 | INFO | Your Edge version and Edge Driver version match
08/29/2024 15:55:31 | INFO | Edge driver present and not blocked by zoning, loading...
08/29/2024 15:56:33 | ERROR | Failed to load Edge driver, cannot continue.  error details: Exception setting "Size": "The HTTP request to the remote WebDriver server for URL http://localhost:54172/session/7f2cf615ca8be375edf2be720479388e/window/rect timed out after 60 seconds."
08/29/2024 15:57:56 | INFO | Restarting Explorer.exe to make the drive(s) visible
08/29/2024 15:57:57 | INFO | Detected running Explorer processes, attempting to shut them down...
08/29/2024 15:57:57 | INFO | Stopped process with handle 22416`

We've deleted the "Lieben Consulting" folder in %appdata%, msedgedriver.exe and WebDriver.dll which usually sorts out any error, but didn't help. 

Any ideas?

James

**Comment by jflieben** [comment]
This was reported by another user as well recently, and fixed in a (very minor) patch here: https://github.com/jflieben/OnedriveMapperV5/blob/main/OneDriveMapper.ps1
